import type { Metadata } from "next";
import { Poppins, Krona_One } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { MobileHeader } from "@/components/Header/MobileHeader";
import { Footer } from "@/components/Footer/Footer";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const kronaOne = Krona_One({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${kronaOne.className} `}>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <div className="h-screen flex flex-col justify-between">
          <Header />
          <MobileHeader />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
